### PR TITLE
Remove redundant rules

### PR DESCRIPTION
**Pull request by IanDelMar**

### CODE REVIEW

**Comment by szepeviktor** [comment]
BTW This ruleset is unused.
I'm not involved in a WordPress project.

**Comment by IanDelMar** [comment]
But it is used in phpstan-wordpress and wordpress-stubs. Do you want me to stop opening PRs for this ruleset?

**Comment by szepeviktor** [comment]
I would like to WORK.

**Comment by szepeviktor** [comment]
@IanDelMar 💣 

```
Referenced sniff "Wordpress.PHP.DontExtract" does not exist
```
from php 7.4 - 8.1

Are we in a rabit hole?

**Comment by IanDelMar** [comment]
This does not answer my question. Does 'I would like to work' mean 'I don't have the time to care about this, please stop bothering me with PRs,' or does it mean 'I would love to work on paid projects, which I am currently not'?

**Comment by IanDelMar** [comment]
> @IanDelMar 💣
> 
> ```
> Referenced sniff "Wordpress.PHP.DontExtract" does not exist
> ```
> 
> from php 7.4 - 8.1 https://github.com/szepeviktor/phpcs-psr-12-neutron-hybrid-ruleset/runs/26838860030
> 
> Are we in a rabbit hole?

https://github.com/WordPress/WordPress-Coding-Standards/blob/develop/WordPress/Sniffs/PHP/DontExtractSniff.php

**Comment by IanDelMar** [comment]
> > @IanDelMar 💣
> > ```
> > Referenced sniff "Wordpress.PHP.DontExtract" does not exist
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > from php 7.4 - 8.1 https://github.com/szepeviktor/phpcs-psr-12-neutron-hybrid-ruleset/runs/26838860030
> > Are we in a rabbit hole?
> 
> https://github.com/WordPress/WordPress-Coding-Standards/blob/develop/WordPress/Sniffs/PHP/DontExtractSniff.php

Maybe I should have put it here:

```
<rule ref="WordPress-Extra">
    <exclude name="Wordpress.PHP.DontExtract"/>
</rule>
```

**Comment by szepeviktor** [comment]
It is in "Core" ruleset.
https://github.com/WordPress/WordPress-Coding-Standards/blob/d77b0204f49e4b4a2bbac791e3bbfbfe603edf06/WordPress-Core/ruleset.xml#L847

**Comment by szepeviktor** [comment]
> Does 'I would like to work' mean 'I don't have the time to care about this, please stop bothering me with PRs,' or does it mean 'I would love to work on paid projects, which I am currently not'?

I can think of one only thing: _I'd like to work_
I cannot answer your question.

How about just pressing the Merge button on your PR-s?

**Pull request merged**
